# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bmp_gen.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class UiBitmapGenerator(object):
    def setupUi(self, BMP_Generator):
        BMP_Generator.setObjectName("BMP_Generator")
        BMP_Generator.resize(398, 300)
        self.tableWidget = QtWidgets.QTableWidget(BMP_Generator)
        self.tableWidget.setGeometry(QtCore.QRect(10, 50, 381, 151))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.tableWidget.setFont(font)
        self.tableWidget.setRowCount(4)
        self.tableWidget.setColumnCount(12)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 11, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(30)
        self.lineEdit_horizontal = QtWidgets.QLineEdit(BMP_Generator)
        self.lineEdit_horizontal.setGeometry(QtCore.QRect(20, 230, 51, 20))
        self.lineEdit_horizontal.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_horizontal.setMaxLength(3)
        self.lineEdit_horizontal.setObjectName("lineEdit_horizontal")
        self.label_Resolution = QtWidgets.QLabel(BMP_Generator)
        self.label_Resolution.setGeometry(QtCore.QRect(20, 210, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setBold(True)
        font.setWeight(75)
        self.label_Resolution.setFont(font)
        self.label_Resolution.setObjectName("label_Resolution")
        self.label_2 = QtWidgets.QLabel(BMP_Generator)
        self.label_2.setGeometry(QtCore.QRect(80, 230, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_vertical = QtWidgets.QLineEdit(BMP_Generator)
        self.lineEdit_vertical.setGeometry(QtCore.QRect(100, 230, 51, 20))
        self.lineEdit_vertical.setObjectName("lineEdit_vertical")
        self.label_Pattern = QtWidgets.QLabel(BMP_Generator)
        self.label_Pattern.setGeometry(QtCore.QRect(30, 20, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setBold(True)
        font.setWeight(75)
        self.label_Pattern.setFont(font)
        self.label_Pattern.setObjectName("label_Pattern")
        self.lineEdit_y = QtWidgets.QLineEdit(BMP_Generator)
        self.lineEdit_y.setGeometry(QtCore.QRect(170, 20, 51, 20))
        self.lineEdit_y.setObjectName("lineEdit_y")
        self.label_4 = QtWidgets.QLabel(BMP_Generator)
        self.label_4.setGeometry(QtCore.QRect(150, 20, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_x = QtWidgets.QLineEdit(BMP_Generator)
        self.lineEdit_x.setGeometry(QtCore.QRect(90, 20, 51, 20))
        self.lineEdit_x.setObjectName("lineEdit_x")
        self.label_Filename = QtWidgets.QLabel(BMP_Generator)
        self.label_Filename.setGeometry(QtCore.QRect(210, 210, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setBold(True)
        font.setWeight(75)
        self.label_Filename.setFont(font)
        self.label_Filename.setObjectName("label_Filename")
        self.lineEdit_Filename = QtWidgets.QLineEdit(BMP_Generator)
        self.lineEdit_Filename.setGeometry(QtCore.QRect(290, 210, 101, 20))
        self.lineEdit_Filename.setText("")
        self.lineEdit_Filename.setObjectName("lineEdit_Filename")
        self.pushButton = QtWidgets.QPushButton(BMP_Generator)
        self.pushButton.setGeometry(QtCore.QRect(310, 270, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(BMP_Generator)
        QtCore.QMetaObject.connectSlotsByName(BMP_Generator)

    def retranslateUi(self, BMP_Generator):
        _translate = QtCore.QCoreApplication.translate
        BMP_Generator.setWindowTitle(_translate("BMP_Generator", "BMP Generator"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("BMP_Generator", "R"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("BMP_Generator", "G"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("BMP_Generator", "B"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("BMP_Generator", "R"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("BMP_Generator", "G"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("BMP_Generator", "B"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("BMP_Generator", "R"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("BMP_Generator", "G"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("BMP_Generator", "B"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("BMP_Generator", "R"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("BMP_Generator", "G"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("BMP_Generator", "B"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(0, 6)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(0, 7)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(0, 8)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(0, 9)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(0, 10)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(0, 11)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(1, 5)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(1, 6)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(1, 7)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(1, 8)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(1, 9)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(1, 10)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(1, 11)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(2, 5)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(2, 6)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(2, 7)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(2, 8)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(2, 9)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(2, 10)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(2, 11)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(3, 5)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(3, 6)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(3, 7)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(3, 8)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(3, 9)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(3, 10)
        item.setText(_translate("BMP_Generator", "0"))
        item = self.tableWidget.item(3, 11)
        item.setText(_translate("BMP_Generator", "0"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.lineEdit_horizontal.setText(_translate("BMP_Generator", "1"))
        self.label_Resolution.setText(_translate("BMP_Generator", "Resolution"))
        self.label_2.setText(_translate("BMP_Generator", "x"))
        self.lineEdit_vertical.setText(_translate("BMP_Generator", "1"))
        self.label_Pattern.setText(_translate("BMP_Generator", "Pattern"))
        self.lineEdit_y.setText(_translate("BMP_Generator", "1"))
        self.label_4.setText(_translate("BMP_Generator", "x"))
        self.lineEdit_x.setText(_translate("BMP_Generator", "1"))
        self.label_Filename.setText(_translate("BMP_Generator", "File Name"))
        self.pushButton.setText(_translate("BMP_Generator", "Generate"))

